Repository startyourlab/website, pull requests merged in 2021-04, with the labels that each got.

#1 Begin organizing sections
  docs/get-started.md
  docusaurus.config.js
  sidebars.js
  src/pages/about.md
  src/pages/markdown-page.md
  src/pages/styles.module.css
  src/pages/support.md
Labels: enhancement

#3 Add google analytics UA property
  docusaurus.config.js
  package.json
Labels: documentation, enhancement

#5 Customize head style
  src/css/custom.css
  src/pages/index.js
  src/pages/styles.module.css
Labels: enhancement

#7 Fix full height hero and make responsive
  src/css/custom.css
Labels: enhancement

#19 Add git goals tutorial
  docs/tutorials/git-goals.md
  sidebars.js
Labels: documentation, enhancement

#21 Add team page components
  community/team.mdx
  src/components/TeamProfileCards/index.js
Labels: enhancement

#22 Add Austin Chustz as industry advisor
  community/team.mdx
  src/components/TeamProfileCards/index.js
Labels: enhancement

#23 Update Austin's bio with Fellow link
  src/components/TeamProfileCards/index.js
Labels: enhancement

#24 Update Ari's bio
  src/components/TeamProfileCards/index.js
Labels: enhancement

#26 Add team description and update git goals
  community/team.mdx
  docs/tutorials/git-goals.md
Labels: enhancement

#31 Adding PSH profile info
  src/components/TeamProfileCards/index.js
  src/css/custom.css
Labels: enhancement

#32 Change "tools configuration" to "setup"
  docs/setup/github-accounts.md
  sidebars.js
Labels: enhancement

#33 Update index page icons and increase header weight
  src/css/custom.css
  static/img/best-practices.svg
  static/img/collaborate-with-digital-tools.svg
  static/img/for-academics.svg
Labels: enhancement

#36 Add contributors page and include labs page
  community/contributing.md
  community/labs.mdx
  community/resources.mdx
  sidebarsCommunity.js
Labels: enhancement

#35 Add Ayush Sood advisor details and bio
  src/components/TeamProfileCards/index.js
Labels: enhancement

#38 Development
  src/components/TeamProfileCards/index.js
Labels: enhancement

#42 Create bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#43 Create feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement, feature

#44 Create documentation_update.md
  .github/ISSUE_TEMPLATE/documentation_update.md
Labels: documentation, feature

#48 Infrastructure update and manifest introduction
  docusaurus.config.js
  package.json
  src/css/custom.css
  static/img/brand-mark.svg
  static/img/brandmark.svg
  static/img/favicons/android-chrome-192x192.png
  static/img/favicons/android-chrome-512x512.png
  static/img/favicons/apple-touch-icon.png
  static/img/favicons/favicon-16x16.png
  static/img/favicons/favicon-32x32.png
  static/img/favicons/site.webmanifest
  static/img/icons/icon-128x128.png
  static/img/icons/icon-144x144.png
  static/img/icons/icon-152x152.png
  static/img/icons/icon-192x192.png
  static/img/icons/icon-384x384.png
  static/img/icons/icon-512x512.png
  static/img/icons/icon-72x72.png
  static/img/icons/icon-96x96.png
  static/img/startyourlab.png
  static/img/startyourlab.svg
  static/manifest.json
  yarn.lock
Labels: enhancement

#47 Add automated APA-style bibliography
  community/resources.mdx
  src/components/Bibliography/index.js
  src/components/Bibliography/styles.module.css
  src/data/bibliography.json
Labels: enhancement, feature

#51 Add operating system tags and draft sections
  docs/setup/github-desktop.mdx
Labels: enhancement, feature

#52 Update git-goals.md
  docs/tutorials/git-goals.md
Labels: enhancement

#54 Add glossary starter
  docs/glossary.md
  sidebars.js
Labels: enhancement, feature

#56 fix: use SVG images with text as outlines
  static/img/setup/github-organization-dark.svg
  static/img/setup/github-organization.svg
Labels: enhancement
